# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuoKe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=128)),
            ],
        ),
    ]
