# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guoke',
            name='author_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
