# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0002_guoke_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guoke',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
