# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author_url', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'guoke',
                'managed': False,
            },
        ),
    ]
