# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0002_douban_huxiu_zhihu'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to=b'')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
